### PR TITLE
Simplify heading parsing

### PR DESCRIPTION
**Pull request by pdamianik**
Simplify heading parsing by not iterating through all the lines in the file and collecting them back into a string.

Sorry saw your GH before you removed it. Its just fair I dox myself as well. Hope you accept PRs :D.

### CODE REVIEW

**Comment by if-loop69420** [comment]
Hey there. 
First of all thank you very much for your contribution :).
Also don't worry, I basically doxxed myself by having bad opsec anyways.
Have you tried if this produces the right titles for the anki cards?

**Comment by if-loop69420** [comment]
I'm just running it myself rn. Trying to see, if the title is removed from the body, like i want it so be

**Comment by pdamianik** [comment]
I more or less tried to run it with and without the change and it seemed like it worked, but you should test it yourself. I could try to create some tests for you.

**Comment by if-loop69420** [comment]
I've ran it. looks good

**Comment by if-loop69420** [comment]
Thank you very much :heart:

**Pull request merged**
